// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

public interface BlocListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:unknow.sync.proto.BlocList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  java.util.List<unknow.sync.proto.BlocInfo> 
      getBlocsList();
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  unknow.sync.proto.BlocInfo getBlocs(int index);
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  int getBlocsCount();
}
