// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

/**
 * Protobuf type {@code unknow.sync.proto.BlocInfo}
 */
public  final class BlocInfo extends
    com.google.protobuf.GeneratedMessageLite<
        BlocInfo, BlocInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:unknow.sync.proto.BlocInfo)
    BlocInfoOrBuilder {
  private BlocInfo() {
  }
  public static final int ROLL_FIELD_NUMBER = 1;
  private int roll_;
  /**
   * <code>fixed32 roll = 1;</code>
   * @return The roll.
   */
  @java.lang.Override
  public int getRoll() {
    return roll_;
  }
  /**
   * <code>fixed32 roll = 1;</code>
   * @param value The roll to set.
   */
  private void setRoll(int value) {
    
    roll_ = value;
  }
  /**
   * <code>fixed32 roll = 1;</code>
   */
  private void clearRoll() {
    
    roll_ = 0;
  }

  public static final int HASH_FIELD_NUMBER = 2;
  private long hash_;
  /**
   * <code>fixed64 hash = 2;</code>
   * @return The hash.
   */
  @java.lang.Override
  public long getHash() {
    return hash_;
  }
  /**
   * <code>fixed64 hash = 2;</code>
   * @param value The hash to set.
   */
  private void setHash(long value) {
    
    hash_ = value;
  }
  /**
   * <code>fixed64 hash = 2;</code>
   */
  private void clearHash() {
    
    hash_ = 0L;
  }

  public static unknow.sync.proto.BlocInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.BlocInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.BlocInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.BlocInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(unknow.sync.proto.BlocInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code unknow.sync.proto.BlocInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        unknow.sync.proto.BlocInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:unknow.sync.proto.BlocInfo)
      unknow.sync.proto.BlocInfoOrBuilder {
    // Construct using unknow.sync.proto.BlocInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>fixed32 roll = 1;</code>
     * @return The roll.
     */
    @java.lang.Override
    public int getRoll() {
      return instance.getRoll();
    }
    /**
     * <code>fixed32 roll = 1;</code>
     * @param value The roll to set.
     * @return This builder for chaining.
     */
    public Builder setRoll(int value) {
      copyOnWrite();
      instance.setRoll(value);
      return this;
    }
    /**
     * <code>fixed32 roll = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoll() {
      copyOnWrite();
      instance.clearRoll();
      return this;
    }

    /**
     * <code>fixed64 hash = 2;</code>
     * @return The hash.
     */
    @java.lang.Override
    public long getHash() {
      return instance.getHash();
    }
    /**
     * <code>fixed64 hash = 2;</code>
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(long value) {
      copyOnWrite();
      instance.setHash(value);
      return this;
    }
    /**
     * <code>fixed64 hash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHash() {
      copyOnWrite();
      instance.clearHash();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:unknow.sync.proto.BlocInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new unknow.sync.proto.BlocInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "roll_",
            "hash_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0006\u0002\u0005" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<unknow.sync.proto.BlocInfo> parser = PARSER;
        if (parser == null) {
          synchronized (unknow.sync.proto.BlocInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<unknow.sync.proto.BlocInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:unknow.sync.proto.BlocInfo)
  private static final unknow.sync.proto.BlocInfo DEFAULT_INSTANCE;
  static {
    BlocInfo defaultInstance = new BlocInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BlocInfo.class, defaultInstance);
  }

  public static unknow.sync.proto.BlocInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BlocInfo> PARSER;

  public static com.google.protobuf.Parser<BlocInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

