// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

/**
 * Protobuf type {@code unknow.sync.proto.BlocList}
 */
public  final class BlocList extends
    com.google.protobuf.GeneratedMessageLite<
        BlocList, BlocList.Builder> implements
    // @@protoc_insertion_point(message_implements:unknow.sync.proto.BlocList)
    BlocListOrBuilder {
  private BlocList() {
    blocs_ = emptyProtobufList();
  }
  public static final int BLOCS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<unknow.sync.proto.BlocInfo> blocs_;
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<unknow.sync.proto.BlocInfo> getBlocsList() {
    return blocs_;
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  public java.util.List<? extends unknow.sync.proto.BlocInfoOrBuilder> 
      getBlocsOrBuilderList() {
    return blocs_;
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  @java.lang.Override
  public int getBlocsCount() {
    return blocs_.size();
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  @java.lang.Override
  public unknow.sync.proto.BlocInfo getBlocs(int index) {
    return blocs_.get(index);
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  public unknow.sync.proto.BlocInfoOrBuilder getBlocsOrBuilder(
      int index) {
    return blocs_.get(index);
  }
  private void ensureBlocsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<unknow.sync.proto.BlocInfo> tmp = blocs_;
    if (!tmp.isModifiable()) {
      blocs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  private void setBlocs(
      int index, unknow.sync.proto.BlocInfo value) {
    value.getClass();
  ensureBlocsIsMutable();
    blocs_.set(index, value);
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  private void addBlocs(unknow.sync.proto.BlocInfo value) {
    value.getClass();
  ensureBlocsIsMutable();
    blocs_.add(value);
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  private void addBlocs(
      int index, unknow.sync.proto.BlocInfo value) {
    value.getClass();
  ensureBlocsIsMutable();
    blocs_.add(index, value);
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  private void addAllBlocs(
      java.lang.Iterable<? extends unknow.sync.proto.BlocInfo> values) {
    ensureBlocsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, blocs_);
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  private void clearBlocs() {
    blocs_ = emptyProtobufList();
  }
  /**
   * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
   */
  private void removeBlocs(int index) {
    ensureBlocsIsMutable();
    blocs_.remove(index);
  }

  public static unknow.sync.proto.BlocList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.BlocList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.BlocList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.BlocList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.BlocList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.BlocList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(unknow.sync.proto.BlocList prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code unknow.sync.proto.BlocList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        unknow.sync.proto.BlocList, Builder> implements
      // @@protoc_insertion_point(builder_implements:unknow.sync.proto.BlocList)
      unknow.sync.proto.BlocListOrBuilder {
    // Construct using unknow.sync.proto.BlocList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<unknow.sync.proto.BlocInfo> getBlocsList() {
      return java.util.Collections.unmodifiableList(
          instance.getBlocsList());
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    @java.lang.Override
    public int getBlocsCount() {
      return instance.getBlocsCount();
    }/**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    @java.lang.Override
    public unknow.sync.proto.BlocInfo getBlocs(int index) {
      return instance.getBlocs(index);
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder setBlocs(
        int index, unknow.sync.proto.BlocInfo value) {
      copyOnWrite();
      instance.setBlocs(index, value);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder setBlocs(
        int index, unknow.sync.proto.BlocInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setBlocs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder addBlocs(unknow.sync.proto.BlocInfo value) {
      copyOnWrite();
      instance.addBlocs(value);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder addBlocs(
        int index, unknow.sync.proto.BlocInfo value) {
      copyOnWrite();
      instance.addBlocs(index, value);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder addBlocs(
        unknow.sync.proto.BlocInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addBlocs(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder addBlocs(
        int index, unknow.sync.proto.BlocInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addBlocs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder addAllBlocs(
        java.lang.Iterable<? extends unknow.sync.proto.BlocInfo> values) {
      copyOnWrite();
      instance.addAllBlocs(values);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder clearBlocs() {
      copyOnWrite();
      instance.clearBlocs();
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.BlocInfo blocs = 1;</code>
     */
    public Builder removeBlocs(int index) {
      copyOnWrite();
      instance.removeBlocs(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:unknow.sync.proto.BlocList)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new unknow.sync.proto.BlocList();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "blocs_",
            unknow.sync.proto.BlocInfo.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<unknow.sync.proto.BlocList> parser = PARSER;
        if (parser == null) {
          synchronized (unknow.sync.proto.BlocList.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<unknow.sync.proto.BlocList>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:unknow.sync.proto.BlocList)
  private static final unknow.sync.proto.BlocList DEFAULT_INSTANCE;
  static {
    BlocList defaultInstance = new BlocList();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BlocList.class, defaultInstance);
  }

  public static unknow.sync.proto.BlocList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BlocList> PARSER;

  public static com.google.protobuf.Parser<BlocList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

