// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

public interface BlocInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:unknow.sync.proto.BlocInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>fixed32 roll = 1;</code>
   * @return The roll.
   */
  int getRoll();

  /**
   * <code>fixed64 hash = 2;</code>
   * @return The hash.
   */
  long getHash();
}
