// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

public interface FileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:unknow.sync.proto.FileInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint64 size = 2;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>fixed64 hash = 3;</code>
   * @return The hash.
   */
  long getHash();
}
