// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

public interface GetBlocOrBuilder extends
    // @@protoc_insertion_point(interface_extends:unknow.sync.proto.GetBloc)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string file = 1;</code>
   * @return The file.
   */
  java.lang.String getFile();
  /**
   * <code>string file = 1;</code>
   * @return The bytes for file.
   */
  com.google.protobuf.ByteString
      getFileBytes();

  /**
   * <code>uint32 bloc = 2;</code>
   * @return The bloc.
   */
  int getBloc();
}
