// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

/**
 * Protobuf type {@code unknow.sync.proto.GetBloc}
 */
public  final class GetBloc extends
    com.google.protobuf.GeneratedMessageLite<
        GetBloc, GetBloc.Builder> implements
    // @@protoc_insertion_point(message_implements:unknow.sync.proto.GetBloc)
    GetBlocOrBuilder {
  private GetBloc() {
    file_ = "";
  }
  public static final int FILE_FIELD_NUMBER = 1;
  private java.lang.String file_;
  /**
   * <code>string file = 1;</code>
   * @return The file.
   */
  @java.lang.Override
  public java.lang.String getFile() {
    return file_;
  }
  /**
   * <code>string file = 1;</code>
   * @return The bytes for file.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(file_);
  }
  /**
   * <code>string file = 1;</code>
   * @param value The file to set.
   */
  private void setFile(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    file_ = value;
  }
  /**
   * <code>string file = 1;</code>
   */
  private void clearFile() {
    
    file_ = getDefaultInstance().getFile();
  }
  /**
   * <code>string file = 1;</code>
   * @param value The bytes for file to set.
   */
  private void setFileBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    file_ = value.toStringUtf8();
    
  }

  public static final int BLOC_FIELD_NUMBER = 2;
  private int bloc_;
  /**
   * <code>uint32 bloc = 2;</code>
   * @return The bloc.
   */
  @java.lang.Override
  public int getBloc() {
    return bloc_;
  }
  /**
   * <code>uint32 bloc = 2;</code>
   * @param value The bloc to set.
   */
  private void setBloc(int value) {
    
    bloc_ = value;
  }
  /**
   * <code>uint32 bloc = 2;</code>
   */
  private void clearBloc() {
    
    bloc_ = 0;
  }

  public static unknow.sync.proto.GetBloc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.GetBloc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.GetBloc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.GetBloc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.GetBloc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.GetBloc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(unknow.sync.proto.GetBloc prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code unknow.sync.proto.GetBloc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        unknow.sync.proto.GetBloc, Builder> implements
      // @@protoc_insertion_point(builder_implements:unknow.sync.proto.GetBloc)
      unknow.sync.proto.GetBlocOrBuilder {
    // Construct using unknow.sync.proto.GetBloc.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string file = 1;</code>
     * @return The file.
     */
    @java.lang.Override
    public java.lang.String getFile() {
      return instance.getFile();
    }
    /**
     * <code>string file = 1;</code>
     * @return The bytes for file.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileBytes() {
      return instance.getFileBytes();
    }
    /**
     * <code>string file = 1;</code>
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(
        java.lang.String value) {
      copyOnWrite();
      instance.setFile(value);
      return this;
    }
    /**
     * <code>string file = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFile() {
      copyOnWrite();
      instance.clearFile();
      return this;
    }
    /**
     * <code>string file = 1;</code>
     * @param value The bytes for file to set.
     * @return This builder for chaining.
     */
    public Builder setFileBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileBytes(value);
      return this;
    }

    /**
     * <code>uint32 bloc = 2;</code>
     * @return The bloc.
     */
    @java.lang.Override
    public int getBloc() {
      return instance.getBloc();
    }
    /**
     * <code>uint32 bloc = 2;</code>
     * @param value The bloc to set.
     * @return This builder for chaining.
     */
    public Builder setBloc(int value) {
      copyOnWrite();
      instance.setBloc(value);
      return this;
    }
    /**
     * <code>uint32 bloc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBloc() {
      copyOnWrite();
      instance.clearBloc();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:unknow.sync.proto.GetBloc)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new unknow.sync.proto.GetBloc();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "file_",
            "bloc_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u000b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<unknow.sync.proto.GetBloc> parser = PARSER;
        if (parser == null) {
          synchronized (unknow.sync.proto.GetBloc.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<unknow.sync.proto.GetBloc>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:unknow.sync.proto.GetBloc)
  private static final unknow.sync.proto.GetBloc DEFAULT_INSTANCE;
  static {
    GetBloc defaultInstance = new GetBloc();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetBloc.class, defaultInstance);
  }

  public static unknow.sync.proto.GetBloc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetBloc> PARSER;

  public static com.google.protobuf.Parser<GetBloc> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

