// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

/**
 * Protobuf type {@code unknow.sync.proto.ProjectInfo}
 */
public  final class ProjectInfo extends
    com.google.protobuf.GeneratedMessageLite<
        ProjectInfo, ProjectInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:unknow.sync.proto.ProjectInfo)
    ProjectInfoOrBuilder {
  private ProjectInfo() {
    file_ = emptyProtobufList();
  }
  public static final int BLOCSIZE_FIELD_NUMBER = 1;
  private int blocSize_;
  /**
   * <code>uint32 blocSize = 1;</code>
   * @return The blocSize.
   */
  @java.lang.Override
  public int getBlocSize() {
    return blocSize_;
  }
  /**
   * <code>uint32 blocSize = 1;</code>
   * @param value The blocSize to set.
   */
  private void setBlocSize(int value) {
    
    blocSize_ = value;
  }
  /**
   * <code>uint32 blocSize = 1;</code>
   */
  private void clearBlocSize() {
    
    blocSize_ = 0;
  }

  public static final int FILE_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<unknow.sync.proto.FileInfo> file_;
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  @java.lang.Override
  public java.util.List<unknow.sync.proto.FileInfo> getFileList() {
    return file_;
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  public java.util.List<? extends unknow.sync.proto.FileInfoOrBuilder> 
      getFileOrBuilderList() {
    return file_;
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  @java.lang.Override
  public int getFileCount() {
    return file_.size();
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  @java.lang.Override
  public unknow.sync.proto.FileInfo getFile(int index) {
    return file_.get(index);
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  public unknow.sync.proto.FileInfoOrBuilder getFileOrBuilder(
      int index) {
    return file_.get(index);
  }
  private void ensureFileIsMutable() {
    com.google.protobuf.Internal.ProtobufList<unknow.sync.proto.FileInfo> tmp = file_;
    if (!tmp.isModifiable()) {
      file_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  private void setFile(
      int index, unknow.sync.proto.FileInfo value) {
    value.getClass();
  ensureFileIsMutable();
    file_.set(index, value);
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  private void addFile(unknow.sync.proto.FileInfo value) {
    value.getClass();
  ensureFileIsMutable();
    file_.add(value);
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  private void addFile(
      int index, unknow.sync.proto.FileInfo value) {
    value.getClass();
  ensureFileIsMutable();
    file_.add(index, value);
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  private void addAllFile(
      java.lang.Iterable<? extends unknow.sync.proto.FileInfo> values) {
    ensureFileIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, file_);
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  private void clearFile() {
    file_ = emptyProtobufList();
  }
  /**
   * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
   */
  private void removeFile(int index) {
    ensureFileIsMutable();
    file_.remove(index);
  }

  public static unknow.sync.proto.ProjectInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.ProjectInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.ProjectInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.ProjectInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(unknow.sync.proto.ProjectInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code unknow.sync.proto.ProjectInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        unknow.sync.proto.ProjectInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:unknow.sync.proto.ProjectInfo)
      unknow.sync.proto.ProjectInfoOrBuilder {
    // Construct using unknow.sync.proto.ProjectInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 blocSize = 1;</code>
     * @return The blocSize.
     */
    @java.lang.Override
    public int getBlocSize() {
      return instance.getBlocSize();
    }
    /**
     * <code>uint32 blocSize = 1;</code>
     * @param value The blocSize to set.
     * @return This builder for chaining.
     */
    public Builder setBlocSize(int value) {
      copyOnWrite();
      instance.setBlocSize(value);
      return this;
    }
    /**
     * <code>uint32 blocSize = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlocSize() {
      copyOnWrite();
      instance.clearBlocSize();
      return this;
    }

    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    @java.lang.Override
    public java.util.List<unknow.sync.proto.FileInfo> getFileList() {
      return java.util.Collections.unmodifiableList(
          instance.getFileList());
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    @java.lang.Override
    public int getFileCount() {
      return instance.getFileCount();
    }/**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    @java.lang.Override
    public unknow.sync.proto.FileInfo getFile(int index) {
      return instance.getFile(index);
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder setFile(
        int index, unknow.sync.proto.FileInfo value) {
      copyOnWrite();
      instance.setFile(index, value);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder setFile(
        int index, unknow.sync.proto.FileInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setFile(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder addFile(unknow.sync.proto.FileInfo value) {
      copyOnWrite();
      instance.addFile(value);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder addFile(
        int index, unknow.sync.proto.FileInfo value) {
      copyOnWrite();
      instance.addFile(index, value);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder addFile(
        unknow.sync.proto.FileInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addFile(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder addFile(
        int index, unknow.sync.proto.FileInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addFile(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder addAllFile(
        java.lang.Iterable<? extends unknow.sync.proto.FileInfo> values) {
      copyOnWrite();
      instance.addAllFile(values);
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder clearFile() {
      copyOnWrite();
      instance.clearFile();
      return this;
    }
    /**
     * <code>repeated .unknow.sync.proto.FileInfo file = 2;</code>
     */
    public Builder removeFile(int index) {
      copyOnWrite();
      instance.removeFile(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:unknow.sync.proto.ProjectInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new unknow.sync.proto.ProjectInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "blocSize_",
            "file_",
            unknow.sync.proto.FileInfo.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u000b\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<unknow.sync.proto.ProjectInfo> parser = PARSER;
        if (parser == null) {
          synchronized (unknow.sync.proto.ProjectInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<unknow.sync.proto.ProjectInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:unknow.sync.proto.ProjectInfo)
  private static final unknow.sync.proto.ProjectInfo DEFAULT_INSTANCE;
  static {
    ProjectInfo defaultInstance = new ProjectInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ProjectInfo.class, defaultInstance);
  }

  public static unknow.sync.proto.ProjectInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProjectInfo> PARSER;

  public static com.google.protobuf.Parser<ProjectInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

