// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

public interface SyncMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:unknow.sync.proto.SyncMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   * @return Whether the project field is set.
   */
  boolean hasProject();
  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   * @return The project.
   */
  unknow.sync.proto.ProjectInfo getProject();

  /**
   * <code>string file = 3;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>string file = 3;</code>
   * @return The file.
   */
  java.lang.String getFile();
  /**
   * <code>string file = 3;</code>
   * @return The bytes for file.
   */
  com.google.protobuf.ByteString
      getFileBytes();

  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   * @return Whether the bloc field is set.
   */
  boolean hasBloc();
  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   * @return The bloc.
   */
  unknow.sync.proto.BlocList getBloc();

  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   * @return Whether the getbloc field is set.
   */
  boolean hasGetbloc();
  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   * @return The getbloc.
   */
  unknow.sync.proto.GetBloc getGetbloc();

  /**
   * <code>bytes data = 6;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>bytes data = 6;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   * @return Whether the getfile field is set.
   */
  boolean hasGetfile();
  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   * @return The getfile.
   */
  unknow.sync.proto.GetFile getGetfile();

  public unknow.sync.proto.SyncMessage.ContentCase getContentCase();
}
