// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package unknow.sync.proto;

/**
 * Protobuf type {@code unknow.sync.proto.SyncMessage}
 */
public  final class SyncMessage extends
    com.google.protobuf.GeneratedMessageLite<
        SyncMessage, SyncMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:unknow.sync.proto.SyncMessage)
    SyncMessageOrBuilder {
  private SyncMessage() {
  }
  private int contentCase_ = 0;
  private java.lang.Object content_;
  public enum ContentCase {
    TOKEN(1),
    PROJECT(2),
    FILE(3),
    BLOC(4),
    GETBLOC(5),
    DATA(6),
    GETFILE(7),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 1: return TOKEN;
        case 2: return PROJECT;
        case 3: return FILE;
        case 4: return BLOC;
        case 5: return GETBLOC;
        case 6: return DATA;
        case 7: return GETFILE;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  private void clearContent() {
    contentCase_ = 0;
    content_ = null;
  }

  public static final int TOKEN_FIELD_NUMBER = 1;
  /**
   * <code>string token = 1;</code>
   * @return Whether the token field is set.
   */
  @java.lang.Override
  public boolean hasToken() {
    return contentCase_ == 1;
  }
  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.String ref = "";
    if (contentCase_ == 1) {
      ref = (java.lang.String) content_;
    }
    return ref;
  }
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.String ref = "";
    if (contentCase_ == 1) {
      ref = (java.lang.String) content_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string token = 1;</code>
   * @param value The token to set.
   */
  private void setToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  contentCase_ = 1;
    content_ = value;
  }
  /**
   * <code>string token = 1;</code>
   */
  private void clearToken() {
    if (contentCase_ == 1) {
      contentCase_ = 0;
      content_ = null;
    }
  }
  /**
   * <code>string token = 1;</code>
   * @param value The bytes for token to set.
   */
  private void setTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    content_ = value.toStringUtf8();
    contentCase_ = 1;
  }

  public static final int PROJECT_FIELD_NUMBER = 2;
  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   */
  @java.lang.Override
  public boolean hasProject() {
    return contentCase_ == 2;
  }
  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   */
  @java.lang.Override
  public unknow.sync.proto.ProjectInfo getProject() {
    if (contentCase_ == 2) {
       return (unknow.sync.proto.ProjectInfo) content_;
    }
    return unknow.sync.proto.ProjectInfo.getDefaultInstance();
  }
  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   */
  private void setProject(unknow.sync.proto.ProjectInfo value) {
    value.getClass();
  content_ = value;
    contentCase_ = 2;
  }
  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   */
  private void mergeProject(unknow.sync.proto.ProjectInfo value) {
    value.getClass();
  if (contentCase_ == 2 &&
        content_ != unknow.sync.proto.ProjectInfo.getDefaultInstance()) {
      content_ = unknow.sync.proto.ProjectInfo.newBuilder((unknow.sync.proto.ProjectInfo) content_)
          .mergeFrom(value).buildPartial();
    } else {
      content_ = value;
    }
    contentCase_ = 2;
  }
  /**
   * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
   */
  private void clearProject() {
    if (contentCase_ == 2) {
      contentCase_ = 0;
      content_ = null;
    }
  }

  public static final int FILE_FIELD_NUMBER = 3;
  /**
   * <code>string file = 3;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return contentCase_ == 3;
  }
  /**
   * <code>string file = 3;</code>
   * @return The file.
   */
  @java.lang.Override
  public java.lang.String getFile() {
    java.lang.String ref = "";
    if (contentCase_ == 3) {
      ref = (java.lang.String) content_;
    }
    return ref;
  }
  /**
   * <code>string file = 3;</code>
   * @return The bytes for file.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileBytes() {
    java.lang.String ref = "";
    if (contentCase_ == 3) {
      ref = (java.lang.String) content_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string file = 3;</code>
   * @param value The file to set.
   */
  private void setFile(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  contentCase_ = 3;
    content_ = value;
  }
  /**
   * <code>string file = 3;</code>
   */
  private void clearFile() {
    if (contentCase_ == 3) {
      contentCase_ = 0;
      content_ = null;
    }
  }
  /**
   * <code>string file = 3;</code>
   * @param value The bytes for file to set.
   */
  private void setFileBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    content_ = value.toStringUtf8();
    contentCase_ = 3;
  }

  public static final int BLOC_FIELD_NUMBER = 4;
  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   */
  @java.lang.Override
  public boolean hasBloc() {
    return contentCase_ == 4;
  }
  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   */
  @java.lang.Override
  public unknow.sync.proto.BlocList getBloc() {
    if (contentCase_ == 4) {
       return (unknow.sync.proto.BlocList) content_;
    }
    return unknow.sync.proto.BlocList.getDefaultInstance();
  }
  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   */
  private void setBloc(unknow.sync.proto.BlocList value) {
    value.getClass();
  content_ = value;
    contentCase_ = 4;
  }
  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   */
  private void mergeBloc(unknow.sync.proto.BlocList value) {
    value.getClass();
  if (contentCase_ == 4 &&
        content_ != unknow.sync.proto.BlocList.getDefaultInstance()) {
      content_ = unknow.sync.proto.BlocList.newBuilder((unknow.sync.proto.BlocList) content_)
          .mergeFrom(value).buildPartial();
    } else {
      content_ = value;
    }
    contentCase_ = 4;
  }
  /**
   * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
   */
  private void clearBloc() {
    if (contentCase_ == 4) {
      contentCase_ = 0;
      content_ = null;
    }
  }

  public static final int GETBLOC_FIELD_NUMBER = 5;
  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   */
  @java.lang.Override
  public boolean hasGetbloc() {
    return contentCase_ == 5;
  }
  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   */
  @java.lang.Override
  public unknow.sync.proto.GetBloc getGetbloc() {
    if (contentCase_ == 5) {
       return (unknow.sync.proto.GetBloc) content_;
    }
    return unknow.sync.proto.GetBloc.getDefaultInstance();
  }
  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   */
  private void setGetbloc(unknow.sync.proto.GetBloc value) {
    value.getClass();
  content_ = value;
    contentCase_ = 5;
  }
  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   */
  private void mergeGetbloc(unknow.sync.proto.GetBloc value) {
    value.getClass();
  if (contentCase_ == 5 &&
        content_ != unknow.sync.proto.GetBloc.getDefaultInstance()) {
      content_ = unknow.sync.proto.GetBloc.newBuilder((unknow.sync.proto.GetBloc) content_)
          .mergeFrom(value).buildPartial();
    } else {
      content_ = value;
    }
    contentCase_ = 5;
  }
  /**
   * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
   */
  private void clearGetbloc() {
    if (contentCase_ == 5) {
      contentCase_ = 0;
      content_ = null;
    }
  }

  public static final int DATA_FIELD_NUMBER = 6;
  /**
   * <code>bytes data = 6;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return contentCase_ == 6;
  }
  /**
   * <code>bytes data = 6;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    if (contentCase_ == 6) {
      return (com.google.protobuf.ByteString) content_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }
  /**
   * <code>bytes data = 6;</code>
   * @param value The data to set.
   */
  private void setData(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  contentCase_ = 6;
    content_ = value;
  }
  /**
   * <code>bytes data = 6;</code>
   */
  private void clearData() {
    if (contentCase_ == 6) {
      contentCase_ = 0;
      content_ = null;
    }
  }

  public static final int GETFILE_FIELD_NUMBER = 7;
  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   */
  @java.lang.Override
  public boolean hasGetfile() {
    return contentCase_ == 7;
  }
  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   */
  @java.lang.Override
  public unknow.sync.proto.GetFile getGetfile() {
    if (contentCase_ == 7) {
       return (unknow.sync.proto.GetFile) content_;
    }
    return unknow.sync.proto.GetFile.getDefaultInstance();
  }
  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   */
  private void setGetfile(unknow.sync.proto.GetFile value) {
    value.getClass();
  content_ = value;
    contentCase_ = 7;
  }
  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   */
  private void mergeGetfile(unknow.sync.proto.GetFile value) {
    value.getClass();
  if (contentCase_ == 7 &&
        content_ != unknow.sync.proto.GetFile.getDefaultInstance()) {
      content_ = unknow.sync.proto.GetFile.newBuilder((unknow.sync.proto.GetFile) content_)
          .mergeFrom(value).buildPartial();
    } else {
      content_ = value;
    }
    contentCase_ = 7;
  }
  /**
   * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
   */
  private void clearGetfile() {
    if (contentCase_ == 7) {
      contentCase_ = 0;
      content_ = null;
    }
  }

  public static unknow.sync.proto.SyncMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.SyncMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.SyncMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static unknow.sync.proto.SyncMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(unknow.sync.proto.SyncMessage prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code unknow.sync.proto.SyncMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        unknow.sync.proto.SyncMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:unknow.sync.proto.SyncMessage)
      unknow.sync.proto.SyncMessageOrBuilder {
    // Construct using unknow.sync.proto.SyncMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ContentCase
        getContentCase() {
      return instance.getContentCase();
    }

    public Builder clearContent() {
      copyOnWrite();
      instance.clearContent();
      return this;
    }


    /**
     * <code>string token = 1;</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return instance.hasToken();
    }
    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return instance.getToken();
    }
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return instance.getTokenBytes();
    }
    /**
     * <code>string token = 1;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setToken(value);
      return this;
    }
    /**
     * <code>string token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      copyOnWrite();
      instance.clearToken();
      return this;
    }
    /**
     * <code>string token = 1;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenBytes(value);
      return this;
    }

    /**
     * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
     */
    @java.lang.Override
    public boolean hasProject() {
      return instance.hasProject();
    }
    /**
     * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
     */
    @java.lang.Override
    public unknow.sync.proto.ProjectInfo getProject() {
      return instance.getProject();
    }
    /**
     * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
     */
    public Builder setProject(unknow.sync.proto.ProjectInfo value) {
      copyOnWrite();
      instance.setProject(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
     */
    public Builder setProject(
        unknow.sync.proto.ProjectInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setProject(builderForValue.build());
      return this;
    }
    /**
     * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
     */
    public Builder mergeProject(unknow.sync.proto.ProjectInfo value) {
      copyOnWrite();
      instance.mergeProject(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.ProjectInfo project = 2;</code>
     */
    public Builder clearProject() {
      copyOnWrite();
      instance.clearProject();
      return this;
    }

    /**
     * <code>string file = 3;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return instance.hasFile();
    }
    /**
     * <code>string file = 3;</code>
     * @return The file.
     */
    @java.lang.Override
    public java.lang.String getFile() {
      return instance.getFile();
    }
    /**
     * <code>string file = 3;</code>
     * @return The bytes for file.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileBytes() {
      return instance.getFileBytes();
    }
    /**
     * <code>string file = 3;</code>
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(
        java.lang.String value) {
      copyOnWrite();
      instance.setFile(value);
      return this;
    }
    /**
     * <code>string file = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFile() {
      copyOnWrite();
      instance.clearFile();
      return this;
    }
    /**
     * <code>string file = 3;</code>
     * @param value The bytes for file to set.
     * @return This builder for chaining.
     */
    public Builder setFileBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileBytes(value);
      return this;
    }

    /**
     * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
     */
    @java.lang.Override
    public boolean hasBloc() {
      return instance.hasBloc();
    }
    /**
     * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
     */
    @java.lang.Override
    public unknow.sync.proto.BlocList getBloc() {
      return instance.getBloc();
    }
    /**
     * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
     */
    public Builder setBloc(unknow.sync.proto.BlocList value) {
      copyOnWrite();
      instance.setBloc(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
     */
    public Builder setBloc(
        unknow.sync.proto.BlocList.Builder builderForValue) {
      copyOnWrite();
      instance.setBloc(builderForValue.build());
      return this;
    }
    /**
     * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
     */
    public Builder mergeBloc(unknow.sync.proto.BlocList value) {
      copyOnWrite();
      instance.mergeBloc(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.BlocList bloc = 4;</code>
     */
    public Builder clearBloc() {
      copyOnWrite();
      instance.clearBloc();
      return this;
    }

    /**
     * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
     */
    @java.lang.Override
    public boolean hasGetbloc() {
      return instance.hasGetbloc();
    }
    /**
     * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
     */
    @java.lang.Override
    public unknow.sync.proto.GetBloc getGetbloc() {
      return instance.getGetbloc();
    }
    /**
     * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
     */
    public Builder setGetbloc(unknow.sync.proto.GetBloc value) {
      copyOnWrite();
      instance.setGetbloc(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
     */
    public Builder setGetbloc(
        unknow.sync.proto.GetBloc.Builder builderForValue) {
      copyOnWrite();
      instance.setGetbloc(builderForValue.build());
      return this;
    }
    /**
     * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
     */
    public Builder mergeGetbloc(unknow.sync.proto.GetBloc value) {
      copyOnWrite();
      instance.mergeGetbloc(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.GetBloc getbloc = 5;</code>
     */
    public Builder clearGetbloc() {
      copyOnWrite();
      instance.clearGetbloc();
      return this;
    }

    /**
     * <code>bytes data = 6;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return instance.hasData();
    }
    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <code>bytes data = 6;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <code>bytes data = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    /**
     * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
     */
    @java.lang.Override
    public boolean hasGetfile() {
      return instance.hasGetfile();
    }
    /**
     * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
     */
    @java.lang.Override
    public unknow.sync.proto.GetFile getGetfile() {
      return instance.getGetfile();
    }
    /**
     * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
     */
    public Builder setGetfile(unknow.sync.proto.GetFile value) {
      copyOnWrite();
      instance.setGetfile(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
     */
    public Builder setGetfile(
        unknow.sync.proto.GetFile.Builder builderForValue) {
      copyOnWrite();
      instance.setGetfile(builderForValue.build());
      return this;
    }
    /**
     * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
     */
    public Builder mergeGetfile(unknow.sync.proto.GetFile value) {
      copyOnWrite();
      instance.mergeGetfile(value);
      return this;
    }
    /**
     * <code>.unknow.sync.proto.GetFile getfile = 7;</code>
     */
    public Builder clearGetfile() {
      copyOnWrite();
      instance.clearGetfile();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:unknow.sync.proto.SyncMessage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new unknow.sync.proto.SyncMessage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "content_",
            "contentCase_",
            unknow.sync.proto.ProjectInfo.class,
            unknow.sync.proto.BlocList.class,
            unknow.sync.proto.GetBloc.class,
            unknow.sync.proto.GetFile.class,
          };
          java.lang.String info =
              "\u0000\u0007\u0001\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u023b\u0000\u0002" +
              "<\u0000\u0003\u023b\u0000\u0004<\u0000\u0005<\u0000\u0006=\u0000\u0007<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<unknow.sync.proto.SyncMessage> parser = PARSER;
        if (parser == null) {
          synchronized (unknow.sync.proto.SyncMessage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<unknow.sync.proto.SyncMessage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:unknow.sync.proto.SyncMessage)
  private static final unknow.sync.proto.SyncMessage DEFAULT_INSTANCE;
  static {
    SyncMessage defaultInstance = new SyncMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SyncMessage.class, defaultInstance);
  }

  public static unknow.sync.proto.SyncMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SyncMessage> PARSER;

  public static com.google.protobuf.Parser<SyncMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

