/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.sync.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(64)
@org.apache.avro.specific.AvroGenerated
public class Hash extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Hash\",\"namespace\":\"unknow.sync.proto\",\"size\":64}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  /** Creates a new Hash */
  public Hash() {
    super();
  }
  
  /** Creates a new Hash with the given bytes */
  public Hash(byte[] bytes) {
    super(bytes);
  }
}
