name: release

on:
  push:
    tags:
      - 'release/*'
env:
  GITHUB_TOKEN: ${{secrets.TOKEN}}

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: Unknow0/package@master

    - name: set version
      run: mvn -B versions:set -DnewVersion=${GITHUB_REF##*/}

    - name: build
      run: mvn -B javadoc:jar source:jar package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: Unknow0/package@master

    - name: set version
      run: mvn -B versions:set -DnewVersion=${GITHUB_REF##*/}

    - name: build
      run: mvn -B package

    - name: Push docker image
      run: |
        echo "${{secrets.GITHUB_TOKEN}}" | docker login docker.pkg.github.com -u Unknow0 --password-stdin
        docker build -f Dockerfile -t docker.pkg.github.com/unknow0/sync/server sync-server/target/
        docker push docker.pkg.github.com/unknow0/sync/server
        docker tag docker.pkg.github.com/unknow0/sync/server docker.pkg.github.com/unknow0/sync/server:${GITHUB_REF##*/}
        docker push docker.pkg.github.com/unknow0/sync/server:${GITHUB_REF##*/}
