name: Maven Package

on:
  push:
    tags:
      - 'release/*'
env:
  GITHUB_TOKEN: ${{secret.TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: set version
      run: mvn -B versions:set -DnewVersion=${GITHUB_REF##*/} -s .github/settings.xml

    - name: build
      run: mvn -B javadoc:jar source:jar package -s .github/settings.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -s .github/settings.xml
