name: release

on:
  push:
    tags:
      - 'release/*'
jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 11
        server-id: repsy
        server-username: MVN_USER
        server-password: MVN_PASS


    - name: set version
      run: mvn -B versions:set -DnewVersion=${GITHUB_REF##*/}

    - name: build
      run: mvn -B javadoc:jar source:jar package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy
      env:
        MVN_USER: ${{secrets.REPSY_USER}}
        MVN_PASS: ${{secrets.REPSY_PASS}}
